# Generated by Django 5.1.2 on 2024-10-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_aboutus_contact_socialmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='icons',
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='link',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
