# Generated by Django 5.1.2 on 2024-10-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_aboutus_isactive_remove_contact_icons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
