# Generated by Django 5.1.2 on 2024-10-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_category_featuredhome_featured_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredhome',
            name='featured_category',
            field=models.ManyToManyField(blank=True, to='store.category'),
        ),
    ]
