# Generated by Django 5.1.2 on 2024-10-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_featuredhome_featured_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredhome',
            name='discountName',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
