# Generated by Django 5.1.2 on 2024-10-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='region',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='counrty',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
