# Generated by Django 5.1.2 on 2024-10-25 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_shippingaddress_region_shippingaddress_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='counrty',
            new_name='country',
        ),
    ]
