export const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST';
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS';
export const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL';


export const FEATURED_ITEMS_REQUEST = 'FEATURED_ITEMS_REQUEST';
export const FEATURED_ITEMS_SUCCESS = 'FEATURED_ITEMS_SUCCESS';
export const FEATURED_ITEMS_FAIL = 'FEATURED_ITEMS_FAIL';
