export const FETCH_HEADERS_REQUEST = 'FETCH_HEADERS_REQUEST';
export const FETCH_HEADERS_SUCCESS = 'FETCH_HEADERS_SUCCESS';
export const FETCH_HEADERS_FAILURE = 'FETCH_HEADERS_FAILURE';


export const FETCH_ABOUT_REQUEST = 'FETCH_ABOUT_REQUEST';
export const FETCH_ABOUT_SUCCESS = 'FETCH_ABOUT_SUCCESS';
export const FETCH_ABOUT_FAILURE = 'FETCH_ABOUT_FAILURE';

export const FETCH_SOCIAL_REQUEST = 'FETCH_SOCIAL_REQUEST';
export const FETCH_SOCIAL_SUCCESS = 'FETCH_SOCIAL_SUCCESS';
export const FETCH_SOCIAL_FAILURE = 'FETCH_SOCIAL_FAILURE';

export const FETCH_CONTACT_REQUEST = 'FETCH_CONTACT_REQUEST';
export const FETCH_CONTACT_SUCCESS = 'FETCH_CONTACT_SUCCESS';
export const FETCH_CONTACT_FAILURE = 'FETCH_CONTACT_FAILURE';